"""Generation loop.

Wires the per-category generators, runs the critic, and persists state:
  scenarios -> generators -> write files -> critic -> save GeneratedTests + Critique.

The loop is non-LLM and deterministic. The LLM-augmented variant (Phase
7) replaces just the generator step with prompt-driven bodies validated
by the same critic.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from ..context.app_entry import AppEntry, detect_app_entry
from ..generators.accessibility_tests import emit_accessibility_tests
from ..generators.api_tests import emit_api_tests
from ..generators.base import GeneratedFile, write_file
from ..generators.performance_tests import emit_performance_tests
from ..generators.regression_tests import emit_regression_tests
from ..generators.security_tests import emit_security_tests
from ..generators.ui_tests import emit_ui_tests
from ..shared.logging import get_logger
from ..state import schemas
from .test_critic import critique_files

log = get_logger("qa_agent.quality.generation_loop")

_SHIM_NAME_TS = "qa-agent.app.ts"
_JEST_CONFIG_NAME = "jest.qa-agent.config.cjs"


def run_generation_loop(
    project_root: Path,
    scenarios: schemas.Scenarios,
    pm: schemas.ProjectMap,
) -> tuple[schemas.GeneratedTests, schemas.Critique]:
    """Generate, write, and critique. Returns the two new state models."""
    target_language = _pick_language(pm)
    log.info("generation: target_language=%s", target_language)

    app_entry = detect_app_entry(project_root)
    files: list[GeneratedFile] = []
    if target_language == "typescript":
        shim = _emit_ts_shim(app_entry)
        if shim is not None:
            files.append(shim)

    if target_language != "typescript" or app_entry is not None:
        files.extend(emit_api_tests(scenarios.entries, target_language))
        files.extend(emit_security_tests(scenarios.entries, target_language))
        if target_language == "typescript":
            files.append(_emit_jest_config())
    else:
        log.info("generation: no app entry detected — skipping jest API/security tests")

    files.extend(emit_ui_tests(scenarios.entries))
    files.extend(emit_accessibility_tests(scenarios.entries))
    files.extend(emit_performance_tests(scenarios.entries))
    files.extend(emit_regression_tests(scenarios.entries, target_language))

    written: list[schemas.GeneratedTest] = []
    by_path: dict[str, GeneratedFile] = {gf.rel_path: gf for gf in files}
    scenario_by_path: dict[str, schemas.Scenario] = {}
    for gf in files:
        if gf.framework == "shim":
            # Helper file (e.g. qa-agent.app.ts) — write but don't register.
            write_file(project_root, gf)
            continue
        # Map back to the originating scenario by id substring in body.
        # (Each generator embeds the scenario id once in the body header.)
        sid = _extract_scenario_id(gf.body)
        sc = next((s for s in scenarios.entries if s.id == sid), None)
        if sc is None:
            continue
        scenario_by_path[gf.rel_path] = sc
        write_file(project_root, gf)
        written.append(
            schemas.GeneratedTest(
                scenario_id=sc.id,
                feature_id=sc.feature_id,
                category=sc.category,
                path=gf.rel_path,
                framework=gf.framework,
                language=gf.language,
                summary=sc.title,
            )
        )

    log.info("generation: wrote %d test files", len(written))
    generated = schemas.GeneratedTests(
        built_at=datetime.now(timezone.utc),
        entries=written,
    )
    critique = critique_files(project_root, generated)
    return generated, critique


def _pick_language(pm: schemas.ProjectMap) -> str:
    """Pick the dominant generator language for the project."""
    py = pm.languages.get("python", 0)
    ts = pm.languages.get("typescript", 0) + pm.languages.get("javascript", 0)
    return "python" if py >= ts else "typescript"


def _extract_scenario_id(body: str) -> str | None:
    marker = "Scenario: "
    idx = body.find(marker)
    if idx == -1:
        return None
    rest = body[idx + len(marker) :]
    end = min((rest.find(c) for c in (".", "\"", "*") if rest.find(c) != -1), default=-1)
    return rest[:end].strip() if end > 0 else rest.split()[0].strip()


def _emit_jest_config() -> GeneratedFile:
    """Emit a jest config that uses ts-jest so TS spec files run.

    The qa-agent jest runner targets this config via `--config` so it
    does not conflict with any project-owned jest config that may exist.
    """
    body = (
        "// Auto-generated by qa-agent. Routes generated TS tests through ts-jest.\n"
        "module.exports = {\n"
        "  preset: 'ts-jest',\n"
        "  testEnvironment: 'node',\n"
        "  testMatch: ['<rootDir>/tests/qa-agent/**/*.spec.ts'],\n"
        "  transform: { '^.+\\\\.tsx?$': ['ts-jest', { diagnostics: false, isolatedModules: true, useESM: false }] },\n"
        "  moduleFileExtensions: ['ts', 'tsx', 'js', 'mjs', 'cjs', 'json'],\n"
        "  // NodeNext-style ESM imports use `.js` even for `.ts` sources; strip the\n"
        "  // suffix so jest can resolve the underlying TypeScript file.\n"
        "  moduleNameMapper: { '^(\\\\.{1,2}/.*)\\\\.js$': '$1' },\n"
        "  testTimeout: 30000,\n"
        "};\n"
    )
    return GeneratedFile(
        rel_path=_JEST_CONFIG_NAME,
        body=body,
        framework="shim",
        language="javascript",
    )


def _emit_ts_shim(app_entry: AppEntry | None) -> GeneratedFile | None:
    """Emit `qa-agent.app.ts` at project root re-exporting the app.

    Tests import `../../../qa-agent.app` consistently. If no app entry was
    detected, returns None so the loop can skip jest-based generation.
    """
    if app_entry is None or app_entry.language not in {"typescript", "javascript"}:
        return None
    rel = app_entry.rel_path
    # Strip extension — TS/JS resolver handles it.
    rel_no_ext = rel.rsplit(".", 1)[0] if "." in rel.rsplit("/", 1)[-1] else rel
    import_target = "./" + rel_no_ext
    if app_entry.has_default_export:
        body = (
            "// Auto-generated by qa-agent. Re-exports the detected app for tests.\n"
            f"export {{ default }} from \"{import_target}\";\n"
        )
    else:
        body = (
            "// Auto-generated by qa-agent. Re-exports the detected app for tests.\n"
            f"import {{ app }} from \"{import_target}\";\n"
            "export default app;\n"
        )
    return GeneratedFile(
        rel_path=_SHIM_NAME_TS,
        body=body,
        framework="shim",
        language="typescript",
    )
