"""Accessibility test generator — Playwright + @axe-core/playwright."""

from __future__ import annotations

from ..state import schemas
from .base import GeneratedFile, slugify


_TEMPLATE = '''/* Auto-generated by qa-agent. Scenario: {sid}. Accessibility/WCAG 2.1 AA. */
import {{ test, expect }} from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

test("{cap} — {title}", async ({{ page }}) => {{
  await page.goto(process.env.QA_BASE_URL ?? "http://localhost:3000/");
  const results = await new AxeBuilder({{ page }})
    .withTags(["wcag2a", "wcag2aa"])
    .analyze();
  const blocking = results.violations.filter(v => v.impact === "critical" || v.impact === "serious");
  expect(blocking, blocking.map(v => v.id).join(", ")).toHaveLength(0);
}});
'''


def emit_accessibility_tests(scenarios: list[schemas.Scenario]) -> list[GeneratedFile]:
    out: list[GeneratedFile] = []
    for sc in scenarios:
        if sc.category != "accessibility":
            continue
        slug = slugify(sc.title)
        rel = f"tests/qa-agent/accessibility/{sc.capability}.{slug}.spec.ts"
        body = _TEMPLATE.format(sid=sc.id, cap=sc.capability, title=sc.title)
        out.append(GeneratedFile(rel_path=rel, body=body, framework="playwright", language="typescript"))
    return out
