"""API test generator.

Emits pytest tests for Python projects (FastAPI/Flask/Starlette) and
jest+supertest tests for Node projects. The body asserts a non-vacuous
contract: status code in expected band, response body non-empty when
expected, error schema present on 4xx.
"""

from __future__ import annotations

from pathlib import Path

from ..state import schemas
from .base import GeneratedFile, effective_request, slugify


def emit_api_tests(
    scenarios: list[schemas.Scenario],
    target_language: str,
) -> list[GeneratedFile]:
    """Return one GeneratedFile per API scenario for the target language."""
    out: list[GeneratedFile] = []
    for sc in scenarios:
        if sc.category != "api":
            continue
        if target_language == "python":
            out.append(_pytest_file(sc))
        else:
            out.append(_jest_file(sc))
    return out


_METHOD_TO_SUPERTEST = {
    "GET": "get",
    "POST": "post",
    "PUT": "put",
    "PATCH": "patch",
    "DELETE": "delete",
    "HEAD": "head",
    "OPTIONS": "options",
}

_PYTEST_METHOD_MAP = {
    "GET": "get",
    "POST": "post",
    "PUT": "put",
    "PATCH": "patch",
    "DELETE": "delete",
}


def _pytest_file(sc: schemas.Scenario) -> GeneratedFile:
    slug = slugify(sc.title)
    rel = f"tests/qa-agent/api/test_{sc.capability}_{slug}.py"
    steps = "\n".join(f"    # {s.keyword.upper()}: {s.text}" for s in sc.steps)
    method, path = effective_request(sc.route)
    py_method = _PYTEST_METHOD_MAP.get(method, "get")
    expected_band = "(400, 500)" if sc.severity == "negative" else "(200, 500)"
    body = f'''"""Auto-generated by qa-agent. Scenario: {sc.id}."""
import pytest


@pytest.mark.qa_agent
def test_{slug.replace("-", "_")}(api_client):
{steps}
    # Target route: {method} {path}
    response = api_client.{py_method}("{path}", headers={{"X-QA-Scenario": "{sc.id}"}})
    assert response.status_code < 500, "server error indicates broken contract"
    assert {expected_band[0]} <= response.status_code < {expected_band[1]}, \\
        f"expected status in band {expected_band}, got {{response.status_code}}"
    if response.status_code >= 400:
        body = response.json()
        assert "detail" in body or "error" in body, "4xx responses must carry an error schema"
    else:
        body = response.json()
        assert body is not None, "2xx responses must carry a non-null body"
'''
    return GeneratedFile(rel_path=rel, body=body, framework="pytest", language="python")


def _jest_file(sc: schemas.Scenario) -> GeneratedFile:
    slug = slugify(sc.title)
    rel = f"tests/qa-agent/api/{sc.capability}.{slug}.spec.ts"
    steps = "\n".join(f"  // {s.keyword.upper()}: {s.text}" for s in sc.steps)
    method, path = effective_request(sc.route)
    ts_method = _METHOD_TO_SUPERTEST.get(method, "get")
    expected_lo, expected_hi = (400, 500) if sc.severity == "negative" else (200, 500)
    write_body = ".send({})" if ts_method in ("post", "put", "patch") else ""
    body = f'''/* Auto-generated by qa-agent. Scenario: {sc.id}. */
/* Target route: {method} {path} */
import request from "supertest";
import {{ describe, it, expect }} from "@jest/globals";
import app from "../../../qa-agent.app";

describe("{sc.capability} — {sc.title}", () => {{
  it("matches the API contract", async () => {{
{steps}
    const response = await request(app)
      .{ts_method}("{path}")
      .set("X-QA-Scenario", "{sc.id}"){write_body};
    expect(response.status).toBeGreaterThanOrEqual({expected_lo});
    expect(response.status).toBeLessThan({expected_hi});
    if (response.status >= 400) {{
      const text = (response.text ?? "").toLowerCase();
      expect(text).not.toContain("traceback");
    }}
  }});
}});
'''
    return GeneratedFile(rel_path=rel, body=body, framework="jest", language="typescript")
