"""API test generator.

Emits pytest tests for Python projects (FastAPI/Flask/Starlette) and
jest+supertest tests for Node projects. The body asserts a non-vacuous
contract: status code in expected band, response body non-empty when
expected, error schema present on 4xx.
"""

from __future__ import annotations

from pathlib import Path

from ..state import schemas
from .base import GeneratedFile, slugify


def emit_api_tests(
    scenarios: list[schemas.Scenario],
    target_language: str,
) -> list[GeneratedFile]:
    """Return one GeneratedFile per API scenario for the target language."""
    out: list[GeneratedFile] = []
    for sc in scenarios:
        if sc.category != "api":
            continue
        if target_language == "python":
            out.append(_pytest_file(sc))
        else:
            out.append(_jest_file(sc))
    return out


def _pytest_file(sc: schemas.Scenario) -> GeneratedFile:
    slug = slugify(sc.title)
    rel = f"tests/qa-agent/api/test_{sc.capability}_{slug}.py"
    steps = "\n".join(f"    # {s.keyword.upper()}: {s.text}" for s in sc.steps)
    body = f'''"""Auto-generated by qa-agent. Scenario: {sc.id}."""
import pytest


@pytest.mark.qa_agent
def test_{slug.replace("-", "_")}(api_client):
{steps}
    response = api_client.request_for_scenario("{sc.id}")
    assert response.status_code < 500, "server error indicates broken contract"
    if response.status_code >= 400:
        body = response.json()
        assert "detail" in body or "error" in body, "4xx responses must carry an error schema"
    else:
        body = response.json()
        assert body is not None, "2xx responses must carry a non-null body"
'''
    return GeneratedFile(rel_path=rel, body=body, framework="pytest", language="python")


def _jest_file(sc: schemas.Scenario) -> GeneratedFile:
    slug = slugify(sc.title)
    rel = f"tests/qa-agent/api/{sc.capability}.{slug}.spec.ts"
    steps = "\n".join(f"  // {s.keyword.toUpperCase() if False else s.keyword.upper()}: {s.text}" for s in sc.steps)
    body = f'''/* Auto-generated by qa-agent. Scenario: {sc.id}. */
import request from "supertest";
import {{ describe, it, expect }} from "@jest/globals";
import app from "../../../src/server";

describe("{sc.capability} — {sc.title}", () => {{
  it("matches the API contract", async () => {{
{steps}
    const response = await request(app).get("/").set("X-QA-Scenario", "{sc.id}");
    expect(response.status).toBeLessThan(500);
    if (response.status >= 400) {{
      expect(response.body).toEqual(expect.objectContaining({{ error: expect.any(String) }}));
    }} else {{
      expect(response.body).not.toBeNull();
    }}
  }});
}});
'''
    return GeneratedFile(rel_path=rel, body=body, framework="jest", language="typescript")
