"""Auto-generated harness files for the QA test suite.

Scaffolded tests assume four supporting files exist under
``tests/qa-agent/``:

  * ``qa-agent.app.ts`` — re-exports the project's actual server app
    so api / security / performance tests can ``import app from
    "../qa-agent.app"``.
  * ``playwright.config.ts`` — wires ``baseURL`` for UI + a11y tests.
  * ``vitest.config.ts`` — limits vitest's test glob to the
    qa-agent directory so the runner does not collide with the
    project's own tests.
  * ``helpers/api-fixtures.ts`` — generic no-op fixture stub the
    body author falls back to when no seeding helper is provided.

This module emits those files in an idempotent, modular way:

  * Detection is signal-based (file contents, dep flags) — no project
    paths or names are hardcoded.
  * Existing files at conventional locations are respected — we never
    overwrite. If a target ships ``playwright.config.ts`` at the root,
    we skip the qa-agent variant.
  * Any failure to detect a value falls back to a documented default
    (vite 5173, supertest's app default, etc.) — never to a guess
    derived from a specific project.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable

from ..shared.logging import get_logger
from ..state import schemas

log = get_logger("qa_agent.generators.harness")


_APP_FILENAME_HINTS = ("app", "server", "main", "index")
_APP_FILE_EXTS = (".ts", ".tsx", ".js", ".mjs")

# Signals that strongly imply a file is the Express/Fastify/Koa entry.
_APP_SIGNAL_RES = (
    re.compile(r"\bapp\.listen\s*\("),
    re.compile(r"\bcreateServer\s*\("),
    re.compile(r"\bcreateApp\s*\("),
    re.compile(r"\bexport\s+default\s+app\b"),
    re.compile(r"\bexport\s*\{\s*app\s*(?:as\s+default\s*)?\}"),
)
_APP_USE_RE = re.compile(r"\bapp\.use\s*\(")

# Default dev-server URLs per UI framework. Generic constants, not
# project-derived — used only when the project does not declare its
# own port via vite/next/etc. config.
_DEFAULT_DEV_URLS = {
    "vite": "http://localhost:5173",
    "next": "http://localhost:3000",
    "fallback": "http://localhost:5173",
}


def emit_harness_files(
    root: Path,
    pm: schemas.ProjectMap,
    generated_test_paths: Iterable[str],
) -> dict[str, str]:
    """Write any missing harness files. Returns a map of
    ``{logical_name: relative_path}`` for every file actually emitted
    (skipped files are absent from the result).
    """
    qa_dir = root / "tests" / "qa-agent"
    qa_dir.mkdir(parents=True, exist_ok=True)

    out: dict[str, str] = {}
    generated = list(generated_test_paths)
    has_api_tests = any(p.startswith("tests/qa-agent/api/") for p in generated)
    has_security_tests = any(p.startswith("tests/qa-agent/security/") for p in generated)
    has_perf_tests = any(p.startswith("tests/qa-agent/performance/") for p in generated)
    has_ui_tests = any(
        p.startswith(("tests/qa-agent/ui/", "tests/qa-agent/accessibility/"))
        for p in generated
    )
    needs_app_shim = has_api_tests or has_security_tests or has_perf_tests

    if needs_app_shim:
        path = _emit_app_shim(root, pm)
        if path:
            out["app_shim"] = path

    if has_ui_tests and not _target_has_playwright_config(root):
        path = _emit_playwright_config(root, pm)
        if path:
            out["playwright_config"] = path

    if has_ui_tests:
        path = _emit_storage_state(root)
        if path:
            out["storage_state"] = path

    if needs_app_shim and pm.test_runners.get("api") == "vitest" and not _target_has_vitest_config(root):
        path = _emit_vitest_config(root)
        if path:
            out["vitest_config"] = path

    if needs_app_shim:
        path = _emit_test_env_setup(root)
        if path:
            out["test_env_setup"] = path

    if needs_app_shim or has_ui_tests:
        path = _emit_fixtures_helper(root)
        if path:
            out["api_fixtures"] = path

    log.info("harness: emitted %s", out or "(nothing new)")
    return out


# ---------------------------------------------------------------------
# App shim
# ---------------------------------------------------------------------

def _emit_app_shim(root: Path, pm: schemas.ProjectMap) -> str | None:
    shim = root / "tests" / "qa-agent" / "qa-agent.app.ts"
    if shim.exists():
        return None

    entry = _detect_app_entry(root, pm)
    qa_dir = shim.parent
    if entry is None:
        body = (
            "// auto-generated by qa-skills.\n"
            "// No server entry was detected automatically.\n"
            "// Edit this file to re-export your Express/Fastify/Koa app, e.g.:\n"
            "//   export { default } from \"<relative path to your app module>\";\n"
            "// Or set QA_API_APP_PATH and have your harness load it dynamically.\n"
            "throw new Error(\n"
            "  \"qa-skills could not auto-detect your server entry. \" +\n"
            "  \"Edit tests/qa-agent/qa-agent.app.ts to re-export your app.\"\n"
            ");\n"
            "export default undefined as unknown;\n"
        )
        log.warning("harness: app entry not detected — emitted placeholder shim")
    else:
        rel = _relative_import_path(qa_dir, entry)
        body = (
            "// auto-generated by qa-skills. Edit only if your app entry moves.\n"
            f"// Detected entry: {entry.relative_to(root).as_posix()}\n"
            f'export {{ default }} from "{rel}";\n'
        )

    shim.write_text(body, encoding="utf-8")
    return shim.relative_to(root).as_posix()


def _detect_app_entry(root: Path, pm: schemas.ProjectMap) -> Path | None:
    """Pick the file most likely to hold the server app instance.

    Heuristic, generic across Express/Fastify/Koa setups:

      1. Restrict to files named like app/server/main/index with a JS/TS
         extension and not under node_modules / dist / .next.
      2. Score each candidate by counting matches of "creation"
         signals (``app.listen``, ``createServer``, etc.) +
         ``app.use(`` mounts, then ``export default app`` presence.
      3. Tie-breakers: filename ``app.*`` > ``server.*`` > ``main.*``
         > ``index.*``; shallower path wins.
    """
    candidates: list[Path] = []
    for f in pm.files:
        path = root / f.path
        if not path.is_file():
            continue
        if path.suffix not in _APP_FILE_EXTS:
            continue
        stem = path.stem.lower()
        if stem not in _APP_FILENAME_HINTS:
            continue
        if any(part in {"node_modules", "dist", "build", ".next", ".nuxt", "coverage"} for part in path.parts):
            continue
        candidates.append(path)

    if not candidates:
        return None

    scored: list[tuple[int, int, int, Path]] = []
    for c in candidates:
        try:
            text = c.read_text(encoding="utf-8")
        except OSError:
            continue
        signal_hits = sum(1 for rx in _APP_SIGNAL_RES if rx.search(text))
        if signal_hits == 0:
            continue
        use_count = len(_APP_USE_RE.findall(text))
        name_rank = _APP_FILENAME_HINTS.index(c.stem.lower())
        # Sort key: more signals first, then more uses, then earlier
        # in the filename hint list, then shallower path.
        scored.append((-signal_hits, -use_count, name_rank, c))

    if not scored:
        return None
    scored.sort(key=lambda t: (t[0], t[1], t[2], len(t[3].parts)))
    return scored[0][3]


def _relative_import_path(from_dir: Path, target_file: Path) -> str:
    """Return a TS-friendly relative import specifier from ``from_dir``
    to ``target_file`` (drops the extension).
    """
    rel = Path(_posix_relative(from_dir.resolve(), target_file.resolve()))
    rel_no_ext = rel.with_suffix("")
    s = rel_no_ext.as_posix()
    if not s.startswith(("./", "../")):
        s = "./" + s
    return s


def _posix_relative(start: Path, target: Path) -> str:
    """``os.path.relpath`` without dragging the os module in. Falls
    back to absolute path on cross-volume situations (Windows etc.).
    """
    try:
        return str(target.relative_to(start)) if start in target.parents else _walk_up_relative(start, target)
    except ValueError:
        return _walk_up_relative(start, target)


def _walk_up_relative(start: Path, target: Path) -> str:
    start_parts = list(start.parts)
    target_parts = list(target.parts)
    i = 0
    while i < min(len(start_parts), len(target_parts)) and start_parts[i] == target_parts[i]:
        i += 1
    up = [".."] * (len(start_parts) - i)
    down = target_parts[i:]
    return "/".join([*up, *down]) or "."


# ---------------------------------------------------------------------
# Playwright config
# ---------------------------------------------------------------------

def _target_has_playwright_config(root: Path) -> bool:
    return any((root / n).exists() for n in (
        "playwright.config.ts", "playwright.config.js", "playwright.config.mjs"
    ))


def _emit_playwright_config(root: Path, pm: schemas.ProjectMap) -> str | None:
    cfg = root / "tests" / "qa-agent" / "playwright.config.ts"
    if cfg.exists():
        return None

    base_url = pm.dev_servers.get("ui") or _DEFAULT_DEV_URLS["fallback"]
    body = (
        "// auto-generated by qa-skills. Override the QA_BASE_URL or\n"
        "// QA_STORAGE_STATE env vars to point at a different host or\n"
        "// session file without editing this config.\n"
        "//\n"
        "// `storageState` loads cookies/localStorage so UI tests start\n"
        "// already authenticated. The shipped placeholder is empty —\n"
        "// fill it via `playwright codegen` against your dev server, or\n"
        "// have a project-specific global-setup script write it.\n"
        'import { defineConfig } from "@playwright/test";\n'
        'import * as path from "path";\n\n'
        "const STORAGE_STATE = process.env.QA_STORAGE_STATE\n"
        '  ?? path.join(__dirname, "storage-state.json");\n\n'
        "export default defineConfig({\n"
        '  testDir: ".",\n'
        '  testMatch: ["ui/**/*.spec.ts", "accessibility/**/*.spec.ts"],\n'
        "  use: {\n"
        f'    baseURL: process.env.QA_BASE_URL ?? "{base_url}",\n'
        "    storageState: STORAGE_STATE,\n"
        "    headless: true,\n"
        "  },\n"
        "});\n"
    )
    cfg.write_text(body, encoding="utf-8")
    return cfg.relative_to(root).as_posix()


def _emit_storage_state(root: Path) -> str | None:
    """Emit an empty Playwright storage-state placeholder. Users fill
    it via ``playwright codegen`` or a project-specific login script.
    Idempotent: never overwrites a non-empty file the user authored.
    """
    target = root / "tests" / "qa-agent" / "storage-state.json"
    if target.exists():
        return None
    target.write_text('{"cookies":[],"origins":[]}\n', encoding="utf-8")
    return target.relative_to(root).as_posix()


# ---------------------------------------------------------------------
# Vitest config
# ---------------------------------------------------------------------

def _target_has_vitest_config(root: Path) -> bool:
    return any((root / n).exists() for n in (
        "vitest.config.ts", "vitest.config.js", "vitest.config.mjs"
    ))


def _emit_vitest_config(root: Path) -> str | None:
    cfg = root / "tests" / "qa-agent" / "vitest.config.ts"
    if cfg.exists():
        return None

    body = (
        "// auto-generated by qa-skills. Limits vitest to the qa-agent\n"
        "// test tree so it does not collide with the project's own tests.\n"
        '// Includes are relative to the project root (vitest CWD).\n'
        '// `setupFiles` runs before any app modules are imported — that\n'
        "// is where env defaults live (so the app's env validator does\n"
        "// not call process.exit during module init).\n"
        'import { defineConfig } from "vitest/config";\n\n'
        "export default defineConfig({\n"
        "  test: {\n"
        "    include: [\n"
        '      "tests/qa-agent/api/**/*.spec.ts",\n'
        '      "tests/qa-agent/security/**/*.spec.ts",\n'
        '      "tests/qa-agent/performance/**/*.spec.ts",\n'
        "    ],\n"
        '    setupFiles: ["./tests/qa-agent/test-env.setup.ts"],\n'
        "    testTimeout: 15000,\n"
        "  },\n"
        "});\n"
    )
    cfg.write_text(body, encoding="utf-8")
    return cfg.relative_to(root).as_posix()


# ---------------------------------------------------------------------
# Env setup
# ---------------------------------------------------------------------

# Generic env vars common to many backend stacks. Values are universal
# placeholders — never derived from the target project. Every line
# uses ??= so any value the user has already exported in their shell
# (or `.env.test`, dotenv preload, etc.) takes precedence.
_ENV_DEFAULTS: list[tuple[str, str, str]] = [
    # (name, default_value, comment)
    ("NODE_ENV", "test", "vitest assumes NODE_ENV is set; many libs branch on it"),
    ("DATABASE_URL", "postgresql://test:test@localhost:5432/qa_agent_test",
     "placeholder URL — most env validators only check format, not reachability"),
    ("REDIS_URL", "redis://localhost:6379/0", "Redis URL placeholder"),
    ("JWT_SECRET", "qa-agent-test-secret-32-character-minimum-placeholder-x",
     "32+ chars to satisfy z.string().min(32)-style validators"),
    ("SESSION_SECRET", "qa-agent-test-session-32-character-minimum-placeholder",
     "session secret placeholder; same length budget as JWT_SECRET"),
    ("COOKIE_SECRET", "qa-agent-test-cookie-32-character-minimum-placeholder",
     "cookie signing secret placeholder"),
    ("ENCRYPTION_KEY", "qa-agent-test-encryption-32-character-minimum-key-placeholder",
     "general-purpose 32+ char encryption key placeholder"),
    ("PORT", "3000",
     "common default; many env validators require 1024-65535. Tests do not actually bind."),
    ("LOG_LEVEL", "error", "quiet noisy app loggers during tests"),
]


def _emit_test_env_setup(root: Path) -> str | None:
    target = root / "tests" / "qa-agent" / "test-env.setup.ts"
    if target.exists():
        return None

    lines = [
        "// auto-generated by qa-skills. Loaded via vitest setupFiles.",
        "// Sets safe placeholder values for env vars that the app's",
        "// validator typically checks at module-import time. Every",
        "// assignment uses ??= so a real value exported by the user",
        "// (shell, .env, dotenv, etc.) is preserved.",
        "//",
        "// This file is generic: values here are universal placeholders,",
        "// not data from any particular project. If your app's env",
        "// validator requires a specific format (e.g. UUID, real DSN),",
        "// edit this file or override the variable in your shell.",
        "",
    ]
    for name, value, comment in _ENV_DEFAULTS:
        if comment:
            lines.append(f"// {comment}")
        lines.append(f'process.env.{name} ??= "{value}";')
        lines.append("")
    body = "\n".join(lines)
    target.write_text(body, encoding="utf-8")
    return target.relative_to(root).as_posix()


# ---------------------------------------------------------------------
# Fixtures helper
# ---------------------------------------------------------------------

def _emit_fixtures_helper(root: Path) -> str | None:
    target = root / "tests" / "qa-agent" / "helpers" / "api-fixtures.ts"
    if target.exists():
        return None
    target.parent.mkdir(parents=True, exist_ok=True)
    body = (
        "/**\n"
        " * Default fixture helper. Generic no-op stub so generated tests load.\n"
        " * Override this file per-project to seed real users / records / cookies.\n"
        " */\n"
        "export interface ApiFixtureHandle {\n"
        "  cleanup: () => Promise<void>;\n"
        "}\n\n"
        "export async function useApiFixtures(\n"
        "  _app: unknown,\n"
        "): Promise<ApiFixtureHandle> {\n"
        "  return { cleanup: async () => {} };\n"
        "}\n"
    )
    target.write_text(body, encoding="utf-8")
    return target.relative_to(root).as_posix()
