"""Performance smoke generator — Playwright timing harness.

Real perf budgets belong in a separate harness; this generator emits a
*smoke* test that asserts the median of N sequential requests stays
under a soft budget. Catches order-of-magnitude regressions.
"""

from __future__ import annotations

from ..state import schemas
from .base import GeneratedFile, slugify


_TEMPLATE = '''/* Auto-generated by qa-agent. Scenario: {sid}. Performance smoke. */
import {{ test, expect }} from "@playwright/test";

const ITERATIONS = 10;
const BUDGET_MS = Number(process.env.QA_PERF_BUDGET_MS ?? 1500);

test("{cap} — performance smoke", async ({{ page }}) => {{
  const samples: number[] = [];
  for (let i = 0; i < ITERATIONS; i++) {{
    const t0 = Date.now();
    await page.goto(process.env.QA_BASE_URL ?? "http://localhost:3000/");
    samples.push(Date.now() - t0);
  }}
  samples.sort((a, b) => a - b);
  const p95 = samples[Math.floor(samples.length * 0.95) - 1] ?? samples[samples.length - 1];
  expect(p95, `p95=${{p95}}ms (samples=${{JSON.stringify(samples)}})`).toBeLessThan(BUDGET_MS);
}});
'''


def emit_performance_tests(scenarios: list[schemas.Scenario]) -> list[GeneratedFile]:
    out: list[GeneratedFile] = []
    for sc in scenarios:
        if sc.category != "performance":
            continue
        slug = slugify(sc.title)
        rel = f"tests/qa-agent/performance/{sc.capability}.{slug}.spec.ts"
        body = _TEMPLATE.format(sid=sc.id, cap=sc.capability)
        out.append(GeneratedFile(rel_path=rel, body=body, framework="playwright", language="typescript"))
    return out
