"""Regression test generator.

Composes existing scenarios into longer golden-path flows. Output is a
pytest file (Python) or a Playwright test (TS) that replays the
scenarios in sequence and asserts none of them regressed.
"""

from __future__ import annotations

from ..state import schemas
from .base import GeneratedFile, slugify


_PYTHON_TEMPLATE = '''"""Auto-generated by qa-agent. Scenario: {sid}. Regression flow."""
import pytest


@pytest.mark.qa_agent
@pytest.mark.regression
def test_{slug}_regression(api_client):
    # Replays the {cap} happy path end-to-end and asserts core invariants
    # are still satisfied. Anti-regression guard for known-fixed bugs.
    history = api_client.replay_flow("{cap}")
    assert history, "no flow history returned"
    statuses = [step.status_code for step in history]
    assert all(s < 500 for s in statuses), f"regression: server errors at {{statuses}}"
    assert all(s < 400 or step.expected_error for s, step in zip(statuses, history)), \\
        "unexpected 4xx in regression flow"
'''


_TS_TEMPLATE = '''/* Auto-generated by qa-agent. Scenario: {sid}. Regression flow. */
import {{ test, expect }} from "@playwright/test";

test("{cap} — regression flow", async ({{ page }}) => {{
  await page.goto(process.env.QA_BASE_URL ?? "http://localhost:3000/");
  // Replay the {cap} happy path; assert invariants hold step by step.
  await expect(page.getByRole("main")).toBeVisible();
  // Followup: load scenario steps from qa-agent state and replay each.
}});
'''


def emit_regression_tests(
    scenarios: list[schemas.Scenario],
    target_language: str,
) -> list[GeneratedFile]:
    out: list[GeneratedFile] = []
    by_capability: dict[str, list[schemas.Scenario]] = {}
    for sc in scenarios:
        if sc.category != "regression":
            continue
        by_capability.setdefault(sc.capability, []).append(sc)

    for cap, group in by_capability.items():
        first = group[0]
        slug = slugify(f"{cap}-regression")
        if target_language == "python":
            rel = f"tests/qa-agent/regression/test_{cap}_regression.py"
            body = _PYTHON_TEMPLATE.format(sid=first.id, slug=slug.replace("-", "_"), cap=cap)
            out.append(GeneratedFile(rel_path=rel, body=body, framework="pytest", language="python"))
        else:
            rel = f"tests/qa-agent/regression/{cap}.regression.spec.ts"
            body = _TS_TEMPLATE.format(sid=first.id, cap=cap)
            out.append(GeneratedFile(rel_path=rel, body=body, framework="playwright", language="typescript"))
    return out
