"""Security test generator — OWASP-aligned, language-aware.

Emits pytest tests for Python and jest tests for Node that target the
top OWASP risks relevant to the scenario:

  - auth: missing-credential rejection, weak-token rejection
  - injection: SQL/command payloads return safe 4xx, no execution
  - sensitive data: 4xx responses do not echo internals (stack/SQL)
"""

from __future__ import annotations

from ..state import schemas
from .base import GeneratedFile, slugify


_PYTHON_TEMPLATE = '''"""Auto-generated by qa-agent. Scenario: {sid}. OWASP-aligned."""
import pytest


@pytest.mark.qa_agent
@pytest.mark.security
def test_{slug}_rejects_unauthenticated(api_client):
    response = api_client.request_for_scenario("{sid}", strip_auth=True)
    assert response.status_code in (401, 403), \\
        f"expected 401/403 for unauthenticated request, got {{response.status_code}}"
    body_text = response.text.lower()
    assert "traceback" not in body_text, "stack trace leaked in error body"
    assert "select " not in body_text, "SQL fragment leaked in error body"


@pytest.mark.qa_agent
@pytest.mark.security
def test_{slug}_rejects_injection(api_client):
    response = api_client.request_for_scenario("{sid}", payload={{"q": "' OR 1=1 --"}})
    assert response.status_code < 500, "injection payload caused server error — possible execution"
    if response.status_code >= 400:
        assert "syntax" not in response.text.lower(), "DB error string leaked"
'''


_TS_TEMPLATE = '''/* Auto-generated by qa-agent. Scenario: {sid}. OWASP-aligned. */
import request from "supertest";
import {{ describe, it, expect }} from "@jest/globals";
import app from "../../../src/server";

describe("{cap} — {title}", () => {{
  it("rejects unauthenticated access", async () => {{
    const r = await request(app).get("/").set("X-QA-Scenario", "{sid}");
    expect([401, 403]).toContain(r.status);
    expect(r.text.toLowerCase()).not.toContain("traceback");
    expect(r.text.toLowerCase()).not.toContain("select ");
  }});

  it("does not execute injection payloads", async () => {{
    const r = await request(app)
      .post("/")
      .set("X-QA-Scenario", "{sid}")
      .send({{ q: "' OR 1=1 --" }});
    expect(r.status).toBeLessThan(500);
    if (r.status >= 400) {{
      expect(r.text.toLowerCase()).not.toContain("syntax");
    }}
  }});
}});
'''


def emit_security_tests(
    scenarios: list[schemas.Scenario],
    target_language: str,
) -> list[GeneratedFile]:
    out: list[GeneratedFile] = []
    for sc in scenarios:
        if sc.category != "security":
            continue
        slug = slugify(sc.title)
        if target_language == "python":
            rel = f"tests/qa-agent/security/test_{sc.capability}_{slug}.py"
            body = _PYTHON_TEMPLATE.format(sid=sc.id, slug=slug.replace("-", "_"))
            out.append(GeneratedFile(rel_path=rel, body=body, framework="pytest", language="python"))
        else:
            rel = f"tests/qa-agent/security/{sc.capability}.{slug}.spec.ts"
            body = _TS_TEMPLATE.format(sid=sc.id, slug=slug, cap=sc.capability, title=sc.title)
            out.append(GeneratedFile(rel_path=rel, body=body, framework="jest", language="typescript"))
    return out
