"""Security test generator — OWASP-aligned, language-aware.

Emits pytest tests for Python and jest tests for Node that target the
top OWASP risks relevant to the scenario:

  - auth: missing-credential rejection, weak-token rejection
  - injection: SQL/command payloads return safe 4xx, no execution
  - sensitive data: 4xx responses do not echo internals (stack/SQL)
"""

from __future__ import annotations

from ..state import schemas
from .base import GeneratedFile, effective_request, slugify


_METHOD_TO_SUPERTEST = {
    "GET": "get",
    "POST": "post",
    "PUT": "put",
    "PATCH": "patch",
    "DELETE": "delete",
}


def emit_security_tests(
    scenarios: list[schemas.Scenario],
    target_language: str,
) -> list[GeneratedFile]:
    out: list[GeneratedFile] = []
    for sc in scenarios:
        if sc.category != "security":
            continue
        if target_language == "python":
            out.append(_pytest_file(sc))
        else:
            out.append(_jest_file(sc))
    return out


def _pytest_file(sc: schemas.Scenario) -> GeneratedFile:
    slug = slugify(sc.title)
    rel = f"tests/qa-agent/security/test_{sc.capability}_{slug}.py"
    method, path = effective_request(sc.route)
    py_method = method.lower() if method.lower() in {"get", "post", "put", "patch", "delete"} else "get"
    body = f'''"""Auto-generated by qa-agent. Scenario: {sc.id}. OWASP-aligned."""
import pytest


@pytest.mark.qa_agent
@pytest.mark.security
def test_{slug.replace("-", "_")}_rejects_unauthenticated(api_client):
    # Target: {method} {path}
    response = api_client.{py_method}("{path}", headers={{"X-QA-Scenario": "{sc.id}"}}, strip_auth=True)
    assert response.status_code in (401, 403, 404), \\
        f"expected 401/403/404 for unauthenticated request, got {{response.status_code}}"
    body_text = response.text.lower()
    assert "traceback" not in body_text, "stack trace leaked in error body"
    assert "select " not in body_text, "SQL fragment leaked in error body"


@pytest.mark.qa_agent
@pytest.mark.security
def test_{slug.replace("-", "_")}_rejects_injection(api_client):
    response = api_client.{py_method}(
        "{path}",
        headers={{"X-QA-Scenario": "{sc.id}"}},
        json={{"q": "' OR 1=1 --"}},
    )
    assert response.status_code < 500, "injection payload caused server error — possible execution"
    if response.status_code >= 400:
        assert "syntax" not in response.text.lower(), "DB error string leaked"
'''
    return GeneratedFile(rel_path=rel, body=body, framework="pytest", language="python")


def _jest_file(sc: schemas.Scenario) -> GeneratedFile:
    slug = slugify(sc.title)
    rel = f"tests/qa-agent/security/{sc.capability}.{slug}.spec.ts"
    method, path = effective_request(sc.route)
    ts_method = _METHOD_TO_SUPERTEST.get(method, "get")
    write_body = ".send({ q: \"' OR 1=1 --\" })" if ts_method in ("post", "put", "patch") else ""
    body = f'''/* Auto-generated by qa-agent. Scenario: {sc.id}. OWASP-aligned. */
/* Target: {method} {path} */
import request from "supertest";
import {{ describe, it, expect }} from "@jest/globals";
import app from "../../../qa-agent.app";

describe("{sc.capability} — {sc.title}", () => {{
  it("rejects unauthenticated access", async () => {{
    const r = await request(app)
      .{ts_method}("{path}")
      .set("X-QA-Scenario", "{sc.id}");
    expect([401, 403, 404]).toContain(r.status);
    const txt = (r.text ?? "").toLowerCase();
    expect(txt).not.toContain("traceback");
    expect(txt).not.toContain("select ");
  }});

  it("does not execute injection payloads", async () => {{
    const r = await request(app)
      .{ts_method}("{path}")
      .set("X-QA-Scenario", "{sc.id}"){write_body};
    expect(r.status).toBeLessThan(500);
    const txt = (r.text ?? "").toLowerCase();
    if (r.status >= 400) {{
      expect(txt).not.toContain("syntax");
    }}
  }});
}});
'''
    return GeneratedFile(rel_path=rel, body=body, framework="jest", language="typescript")
