"""UI test generator — Playwright (TypeScript)."""

from __future__ import annotations

from ..state import schemas
from .base import GeneratedFile, slugify


def emit_ui_tests(scenarios: list[schemas.Scenario]) -> list[GeneratedFile]:
    out: list[GeneratedFile] = []
    for sc in scenarios:
        if sc.category != "ui":
            continue
        out.append(_playwright_file(sc))
    return out


def _playwright_file(sc: schemas.Scenario) -> GeneratedFile:
    slug = slugify(sc.title)
    rel = f"tests/qa-agent/ui/{sc.capability}.{slug}.spec.ts"
    steps = "\n".join(f"  // {s.keyword.upper()}: {s.text}" for s in sc.steps)
    body = f'''/* Auto-generated by qa-agent. Scenario: {sc.id}. */
import {{ test, expect }} from "@playwright/test";

test("{sc.capability} — {sc.title}", async ({{ page }}) => {{
{steps}
  await page.goto(process.env.QA_BASE_URL ?? "http://localhost:3000/");
  await expect(page).toHaveTitle(/\\S/, {{ timeout: 10_000 }});
  const main = page.getByRole("main");
  await expect(main).toBeVisible();
  // Prefer role / text / data-testid selectors over CSS/XPath.
  // Followups: add scenario-specific actions before the assertions above.
}});
'''
    return GeneratedFile(rel_path=rel, body=body, framework="playwright", language="typescript")
