"""UI test generator — Playwright (TypeScript)."""

from __future__ import annotations

from ..state import schemas
from .base import GeneratedFile, slugify


def emit_ui_tests(scenarios: list[schemas.Scenario]) -> list[GeneratedFile]:
    out: list[GeneratedFile] = []
    for sc in scenarios:
        if sc.category != "ui":
            continue
        out.append(_playwright_file(sc))
    return out


def _playwright_file(sc: schemas.Scenario) -> GeneratedFile:
    slug = slugify(sc.title)
    rel = f"tests/qa-agent/ui/{sc.capability}.{slug}.spec.ts"
    steps = "\n".join(f"  // {s.keyword.upper()}: {s.text}" for s in sc.steps)
    # Heuristic SPA path: `/<capability>` so the navigation actually points
    # somewhere feature-specific. `QA_UI_BASE` lets the operator override.
    feature_path = f"/{sc.capability}"
    body = f'''/* Auto-generated by qa-agent. Scenario: {sc.id}. */
import {{ test, expect }} from "@playwright/test";

test("{sc.capability} — {sc.title}", async ({{ page }}) => {{
{steps}
  const base = process.env.QA_UI_BASE ?? process.env.QA_BASE_URL ?? "http://localhost:3000";
  const consoleErrors: string[] = [];
  page.on("console", (msg) => {{
    if (msg.type() === "error") consoleErrors.push(msg.text());
  }});
  const response = await page.goto(base + "{feature_path}", {{ waitUntil: "domcontentloaded", timeout: 20_000 }});
  expect(response, "navigation must produce a response").not.toBeNull();
  expect(response!.status(), "page must not return a 5xx").toBeLessThan(500);
  await expect(page).toHaveTitle(/\\S/, {{ timeout: 20_000 }});
  // Prefer role / text / data-testid selectors over CSS/XPath.
  const heading = page.getByRole("heading").first();
  await heading.waitFor({{ state: "visible", timeout: 10_000 }}).catch(() => {{ /* page may be a redirect */ }});
  expect(consoleErrors, `console errors: ${{consoleErrors.join("; ")}}`).toHaveLength(0);
}});
'''
    return GeneratedFile(rel_path=rel, body=body, framework="playwright", language="typescript")
