"""Self-contained HTML report renderer (stdlib only).

Replaces the qa-html-reporter LLM agent for the templating step. No CDN, no
external CSS/JS. Reads `report-data.json`, writes a single HTML file.
"""

from __future__ import annotations

import html
import json
from datetime import datetime
from pathlib import Path
from typing import Any

CSS = """
:root {
  --red: #E53E3E; --orange: #DD6B20; --green: #38A169; --gray: #718096;
  --bg: #F7FAFC; --surface: #FFFFFF; --border: #E2E8F0;
  --text-primary: #2D3748; --text-secondary: #718096;
  --badge-passed: #C6F6D5; --badge-partial: #FEFCBF;
  --badge-error: #FED7D7; --badge-skipped: #EDF2F7;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #1A202C; --surface: #2D3748; --border: #4A5568;
    --text-primary: #E2E8F0; --text-secondary: #A0AEC0;
    --badge-passed: #22543D; --badge-partial: #744210;
    --badge-error: #742A2A; --badge-skipped: #2D3748;
  }
}
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; background: var(--bg); color: var(--text-primary); font-family: system-ui, -apple-system, sans-serif; }
body[dir="rtl"] { direction: rtl; }
.container { max-width: 1100px; margin: 0 auto; padding: 24px; }
header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; }
h1 { font-size: 22px; margin: 0; }
.muted { color: var(--text-secondary); font-size: 14px; }
.score-card { background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 24px; text-align: center; margin-bottom: 24px; }
.score { font-size: 64px; font-weight: 700; line-height: 1; }
.score.green { color: var(--green); }
.score.orange { color: var(--orange); }
.score.red { color: var(--red); }
.section { background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 20px; margin-bottom: 16px; }
.section h2 { font-size: 16px; margin: 0 0 12px 0; }
.cat-row { display: flex; align-items: center; gap: 12px; padding: 8px 0; border-bottom: 1px solid var(--border); }
.cat-row:last-child { border-bottom: 0; }
.cat-name { width: 100px; font-weight: 600; }
.bar { flex: 1; height: 8px; background: var(--border); border-radius: 4px; overflow: hidden; }
.bar-fill { height: 100%; background: var(--green); transition: width 0.2s; }
.bar-fill.orange { background: var(--orange); }
.bar-fill.red { background: var(--red); }
.cat-pct { width: 50px; text-align: right; font-variant-numeric: tabular-nums; }
.cat-total { width: 90px; font-size: 12px; color: var(--text-secondary); }
.badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; }
.badge.passed { background: var(--badge-passed); }
.badge.partial { background: var(--badge-partial); }
.badge.error { background: var(--badge-error); }
.badge.skipped { background: var(--badge-skipped); }
details { margin-top: 8px; }
summary { cursor: pointer; color: var(--text-secondary); font-size: 13px; }
ul.missing { margin: 8px 0 0 20px; padding: 0; font-family: ui-monospace, monospace; font-size: 12px; color: var(--text-secondary); }
ul.missing li { margin: 2px 0; }
table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 13px; }
th, td { padding: 8px; text-align: left; border-bottom: 1px solid var(--border); }
.gap-high { color: var(--red); font-weight: 600; }
.gap-medium { color: var(--orange); }
.gap-low { color: var(--text-secondary); }
"""

I18N = {
    "en": {
        "title":      "QA-Skills Report",
        "score":      "Quality score",
        "coverage":   "Coverage by category",
        "uncovered":  "Uncovered",
        "all_covered":"All covered",
        "na":         "N/A — no signal in this project",
        "gaps":       "Gaps",
        "flaky":      "Flaky tests",
        "vulns":      "Vulnerabilities found",
        "timeline":   "Timeline",
        "footer":     "Generated by QA-Skills",
    },
    "he": {
        "title":      "דוח QA-Skills",
        "score":      "ציון איכות",
        "coverage":   "כיסוי לפי קטגוריה",
        "uncovered":  "לא מכוסים",
        "all_covered":"הכל מכוסה",
        "na":         "לא רלוונטי — אין סיגנל בפרויקט",
        "gaps":       "פערים",
        "flaky":      "בדיקות לא יציבות",
        "vulns":      "פגיעויות שנמצאו",
        "timeline":   "ציר זמן",
        "footer":     "נוצר ע\"י QA-Skills",
    },
}


def _esc(s: Any) -> str:
    return html.escape(str(s)) if s is not None else ""


def _score_color(score: int) -> str:
    if score >= 80:
        return "green"
    if score >= 50:
        return "orange"
    return "red"


def _bar_color(pct: int) -> str:
    if pct >= 80:
        return ""
    if pct >= 40:
        return "orange"
    return "red"


def _render_category(cat: str, info: dict, t: dict) -> str:
    status = info.get("status", "skipped:not_generated")
    badge_kind = "passed" if status == "passed" else \
                 "partial" if status == "partial" else \
                 "error" if status == "error" else "skipped"

    total = info.get("total", 0)
    pct = info.get("pct", 0)
    covered = len(info.get("covered_items") or [])
    missing = info.get("missing_items") or []

    if total == 0:
        body = f'<span class="muted">{_esc(t["na"])}</span>'
        bar = ''
    else:
        bar_cls = _bar_color(pct)
        bar = f'<div class="bar"><div class="bar-fill {bar_cls}" style="width:{pct}%"></div></div>'
        if not missing:
            body = f'<span class="muted">{_esc(t["all_covered"])} ✅</span>'
        else:
            items = "".join(f"<li>{_esc(m)}</li>" for m in missing)
            body = f'<details><summary>{_esc(t["uncovered"])} ({len(missing)})</summary><ul class="missing">{items}</ul></details>'

    return f"""
    <div class="cat-row">
      <span class="cat-name">{_esc(cat)}</span>
      {bar}
      <span class="cat-pct">{pct}%</span>
      <span class="cat-total">{covered}/{total}</span>
      <span class="badge {badge_kind}">{_esc(status)}</span>
    </div>
    {body}
    """


def _render_gaps(gaps: list[dict], t: dict) -> str:
    if not gaps:
        return ""
    rows = "".join(
        f'<tr><td class="gap-{_esc(g.get("severity","low"))}">{_esc(g.get("severity"))}</td>'
        f'<td>{_esc(g.get("path"))}</td><td>{_esc(g.get("reason"))}</td></tr>'
        for g in gaps
    )
    return f"""
    <div class="section">
      <h2>{_esc(t["gaps"])}</h2>
      <table><thead><tr><th>severity</th><th>path</th><th>reason</th></tr></thead>
      <tbody>{rows}</tbody></table>
    </div>
    """


def _render_flaky(flaky: list[dict], t: dict) -> str:
    if not flaky:
        return ""
    rows = "".join(
        f'<tr><td>{_esc(f.get("id"))}</td>'
        f'<td>{_esc(f.get("pass_rate"))}</td>'
        f'<td>{_esc(f.get("cause_hypothesis"))}</td>'
        f'<td>{_esc(f.get("suggested_fix"))}</td></tr>'
        for f in flaky
    )
    return f"""
    <div class="section">
      <h2>{_esc(t["flaky"])}</h2>
      <table><thead><tr><th>test</th><th>pass_rate</th><th>cause</th><th>fix</th></tr></thead>
      <tbody>{rows}</tbody></table>
    </div>
    """


def _render_timeline(timeline: list[dict], t: dict) -> str:
    if not timeline:
        return ""
    rows = "".join(
        f'<tr><td>{_esc(p.get("phase"))}</td><td>{_esc(p.get("started_at"))}</td>'
        f'<td>{_esc(p.get("duration_ms",0))} ms</td><td>{_esc(p.get("status",""))}</td></tr>'
        for p in timeline
    )
    return f"""
    <div class="section">
      <h2>{_esc(t["timeline"])}</h2>
      <table><thead><tr><th>phase</th><th>started</th><th>duration</th><th>status</th></tr></thead>
      <tbody>{rows}</tbody></table>
    </div>
    """


def render_html(report_data: dict) -> str:
    locale = report_data.get("locale", "en")
    t = I18N.get(locale, I18N["en"])
    score = int(report_data.get("quality_score", 0))
    score_color = _score_color(score)
    rtl = ' dir="rtl"' if locale == "he" else ""

    coverage_html = "\n".join(
        _render_category(cat, info, t)
        for cat, info in (report_data.get("coverage_by_category") or {}).items()
    )

    gaps_html = _render_gaps(report_data.get("gaps") or [], t)
    flaky_html = _render_flaky(report_data.get("flaky_tests") or [], t)
    timeline_html = _render_timeline(report_data.get("timeline") or [], t)

    project = _esc(report_data.get("project_root", ""))
    generated = _esc(report_data.get("generated_at", ""))

    return f"""<!doctype html>
<html lang="{locale}"{rtl}>
<head>
<meta charset="utf-8">
<title>{_esc(t["title"])}</title>
<style>{CSS}</style>
</head>
<body{rtl}>
<div class="container">
  <header>
    <div>
      <h1>{_esc(t["title"])}</h1>
      <div class="muted">{project}</div>
    </div>
    <div class="muted">{generated}</div>
  </header>

  <div class="score-card">
    <div class="muted">{_esc(t["score"])}</div>
    <div class="score {score_color}">{score}<span style="font-size:24px">/100</span></div>
  </div>

  <div class="section">
    <h2>{_esc(t["coverage"])}</h2>
    {coverage_html}
  </div>

  {gaps_html}
  {flaky_html}
  {timeline_html}

  <footer class="muted" style="text-align:center;padding:20px;">{_esc(t["footer"])}</footer>
</div>
</body></html>"""


def write_html_report(report_data: dict, out_path: str | Path) -> Path:
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_html(report_data), encoding="utf-8")
    return out


__all__ = ["render_html", "write_html_report"]


# CLI wrapper: skills/_shared/scripts/html_render.py
if __name__ == "__main__":
    import argparse
    import sys

    parser = argparse.ArgumentParser(prog="qa_skills.html_render")
    parser.add_argument("--report-data", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    data = json.loads(Path(args.report_data).read_text(encoding="utf-8"))
    out = write_html_report(data, args.out)
    print(json.dumps({"status": "completed", "html_report_path": str(out)}))
    sys.exit(0)
