#!/usr/bin/env python3
"""
Deep structural validation of the HTML report generated by html-reporter.
Usage: python validate_html_report.py <path-to-report.html>

Checks:
  - Self-contained (no external references)
  - All required sections present
  - Gauge math correct (stroke-dasharray values)
  - Filter/search JavaScript present and callable
  - Dark mode CSS present
  - Accessibility: lang attribute, aria labels on interactive elements
"""

import argparse
import re
import sys
from pathlib import Path

PASS = "\033[92m✓\033[0m"
FAIL = "\033[91m✗\033[0m"
failures = []


def ok(msg): print(f"  {PASS} {msg}")


def fail(msg):
    failures.append(msg)
    print(f"  {FAIL} {msg}")


def check(cond, pass_msg, fail_msg=None):
    if cond:
        ok(pass_msg)
    else:
        fail(fail_msg or pass_msg)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("html_file", help="Path to HTML report")
    args = parser.parse_args()

    path = Path(args.html_file)
    if not path.exists():
        print(f"File not found: {path}")
        sys.exit(1)

    content = path.read_text(encoding="utf-8")
    print(f"\n{'='*60}")
    print(f" HTML Report: {path.name} ({len(content):,} bytes)")
    print(f"{'='*60}")

    # ── Self-contained ──────────────────────────────────────────────
    print("\n[Self-contained]")
    external_css = re.findall(r'<link[^>]+href=["\']https?://[^"\']+["\']', content)
    check(not external_css, "No external CSS links", f"External CSS: {external_css}")

    external_js = re.findall(r'<script[^>]+src=["\']https?://[^"\']+["\']', content)
    check(not external_js, "No external JS links", f"External JS: {external_js}")

    check("fonts.googleapis.com" not in content, "No Google Fonts CDN")
    check("cdn.jsdelivr.net" not in content, "No jsdelivr CDN")
    check("unpkg.com" not in content, "No unpkg CDN")

    # ── HTML structure ──────────────────────────────────────────────
    print("\n[HTML structure]")
    check(re.search(r'<!DOCTYPE html>', content, re.IGNORECASE), "DOCTYPE html present")
    check('<html' in content, "<html> tag present")
    check('lang=' in content, 'lang attribute on <html>')
    check('<head>' in content, "<head> present")
    check('<meta charset=' in content, "charset meta present")
    check('<meta name="viewport"' in content, "viewport meta present")
    check('<title>' in content, "<title> present")
    check('<style>' in content and '</style>' in content, "Inline <style> block")
    check('<script>' in content and '</script>' in content, "Inline <script> block")

    # ── Required sections ────────────────────────────────────────────
    print("\n[Required sections]")
    check(re.search(r'class=["\'][^"\']*header', content), "Header section present")
    check(re.search(r'class=["\'][^"\']*scorecard|gauge', content), "Scorecard/gauge section present")
    check(re.search(r'timeline|What was done', content, re.IGNORECASE), "Timeline section present")
    check(re.search(r'module-table|modules-section', content), "Module table present")
    check(re.search(r'gaps-section|Coverage Gaps', content, re.IGNORECASE), "Gaps section present")
    check(re.search(r'blind.?spot', content, re.IGNORECASE), "Blind spots section present")
    check(re.search(r'recommend', content, re.IGNORECASE), "Recommendations section present")
    check('<footer' in content or 'class="footer"' in content, "Footer present")
    check('test-state.json' in content, "Footer links to test-state.json")

    # ── Gauge SVG ────────────────────────────────────────────────────
    print("\n[Gauge SVG]")
    gauge_circles = re.findall(r'stroke-dasharray=["\']([^"\']+)["\']', content)
    check(len(gauge_circles) >= 4, f"At least 4 gauge stroke-dasharray (found {len(gauge_circles)})")

    for i, arr in enumerate(gauge_circles[:4]):
        parts = arr.strip().split()
        if len(parts) == 2:
            try:
                arc = float(parts[0])
                full = float(parts[1])
                check(0 <= arc <= full + 1,
                      f"Gauge {i+1}: arc {arc:.1f} <= full circumference {full:.1f}",
                      f"Gauge {i+1}: arc {arc:.1f} > circumference {full:.1f} — math error")
            except ValueError:
                fail(f"Gauge {i+1}: cannot parse stroke-dasharray '{arr}'")

    # Category labels
    for cat in ["Unit", "UI", "API", "Security"]:
        check(cat in content, f"Category label '{cat}' present in gauges")

    # ── Filter/search JS ─────────────────────────────────────────────
    print("\n[Interactive JavaScript]")
    check("function filterModules" in content, "filterModules function defined")
    check("function searchModules" in content, "searchModules function defined")
    check("data-status" in content, "data-status attributes on module rows")
    check("data-has-blindspots" in content or "data-blindspots" in content, "blind-spot filter data attr present")
    check("oninput" in content or "addEventListener" in content, "Input event handler wired")

    # ── CSS design tokens ────────────────────────────────────────────
    print("\n[CSS design tokens]")
    check("#E53E3E" in content or "E53E3E" in content, "Red token #E53E3E present")
    check("#38A169" in content or "38A169" in content, "Green token #38A169 present")
    check("#DD6B20" in content or "DD6B20" in content, "Orange token #DD6B20 present")
    check("system-ui" in content, "system-ui font family used (no external font)")
    check("prefers-color-scheme: dark" in content, "Dark mode media query present")
    check("--bg:" in content or "var(--bg)" in content, "CSS custom properties used")

    # ── Status badges ────────────────────────────────────────────────
    print("\n[Status badges]")
    for status in ["covered", "partial", "uncovered", "unchanged"]:
        check(f"status-badge {status}" in content or f'status-badge" {status}' in content
              or f'class="{status}"' in content or f"status-badge.{status}" in content,
              f"Status badge '{status}' styled in CSS")

    # ── No sensitive data ────────────────────────────────────────────
    print("\n[No sensitive data]")
    check("passwordHash" not in content, "passwordHash not in report HTML")
    check("password_hash" not in content, "password_hash not in report HTML")
    check("JWT_SECRET" not in content, "JWT_SECRET not in report HTML")

    # ── Results ──────────────────────────────────────────────────────
    print(f"\n{'='*60}")
    print(f" Results: {len(failures)} failed of {len(failures) + sum(1 for _ in [1]*0)}")

    total_checks = failures.__len__() + content.count(PASS)
    print(f" {len(failures)} failures")
    print(f"{'='*60}\n")

    if failures:
        for f in failures:
            print(f"  - {f}")
        sys.exit(1)
    else:
        print("All HTML report checks passed.")
        sys.exit(0)


if __name__ == "__main__":
    main()
