"""Self-healing engine.

For each failing test, classify the failure, look up an allowed action
in the policy, and apply a *bounded* mutation. The engine never weakens
assertions or mutes failures — only does conservative, additive fixes
like inserting a `await page.waitForLoadState` before an assertion or
adding a missing dep to the install plan.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from ..context.app_entry import detect_app_entry
from ..shared.logging import get_logger
from .classifiers import classify_failure
from .policies import DEFAULT_POLICY, FixAction, Policy, pick_action

log = get_logger("qa_agent.healing.engine")


@dataclass(slots=True)
class HealAttempt:
    test_path: str
    failure_category: str
    action: FixAction
    applied: bool
    note: str = ""


def heal_failures(
    project_root: Path,
    failures: Iterable[tuple[str, str]],  # (test_path, log_text)
    policy: Policy = DEFAULT_POLICY,
) -> list[HealAttempt]:
    """Try to heal each failing test. Returns one HealAttempt per input."""
    attempts: list[HealAttempt] = []
    for test_path, log_text in failures:
        cat = classify_failure(log_text)
        action = pick_action(cat, policy)
        applied = False
        note = ""
        try:
            if action == "add-wait":
                applied = _inject_wait(project_root / test_path)
                note = "inserted explicit wait before first assertion"
            elif action == "increase-timeout":
                applied = _bump_timeout(project_root / test_path)
                note = "doubled test timeout"
            elif action == "install-missing-dep":
                note = "deferred to install_manager — engine emits action only"
            elif action == "fix-import-path":
                applied, note = _fix_import_path(project_root, log_text)
            else:
                note = "manual fix required"
        except Exception as e:  # noqa: BLE001 — never crash the run on a heal failure
            log.warning("heal: %s on %s raised %s", action, test_path, e)
            note = f"heal raised: {e}"

        attempts.append(
            HealAttempt(
                test_path=test_path,
                failure_category=cat,
                action=action,
                applied=applied,
                note=note,
            )
        )
    return attempts


# ---- Concrete fix actions --------------------------------------------------

def _inject_wait(path: Path) -> bool:
    """Insert `await page.waitForLoadState('networkidle')` before the first
    `expect(` in a Playwright test. No-op for python/jest files.
    """
    if not path.exists() or path.suffix not in {".ts", ".tsx", ".js"}:
        return False
    src = path.read_text(encoding="utf-8")
    if "waitForLoadState" in src:
        return False  # already waited
    marker = "await expect("
    idx = src.find(marker)
    if idx == -1:
        return False
    head, tail = src[:idx], src[idx:]
    new = head + "await page.waitForLoadState('networkidle');\n  " + tail
    path.write_text(new, encoding="utf-8")
    return True


def _fix_import_path(project_root: Path, log_text: str) -> tuple[bool, str]:
    """Re-detect the app entry and rewrite the project-root shim.

    The shim (`qa-agent.app.ts`) drives every generated jest test, so
    fixing it once heals all affected files at the framework level
    without touching individual tests.
    """
    import re

    entry = detect_app_entry(project_root)
    if entry is None:
        return False, "no app entry detected — manual fix required"
    if entry.language not in {"typescript", "javascript"}:
        return False, f"unsupported language: {entry.language}"

    shim_path = project_root / "qa-agent.app.ts"
    rel_no_ext = entry.rel_path.rsplit(".", 1)[0] if "." in entry.rel_path.rsplit("/", 1)[-1] else entry.rel_path
    import_target = "./" + rel_no_ext
    if entry.has_default_export:
        body = (
            "// Auto-generated by qa-agent (healing). Re-exports the detected app for tests.\n"
            f"export {{ default }} from \"{import_target}\";\n"
        )
    else:
        body = (
            "// Auto-generated by qa-agent (healing). Re-exports the detected app for tests.\n"
            f"import {{ app }} from \"{import_target}\";\n"
            "export default app;\n"
        )
    previous = shim_path.read_text(encoding="utf-8") if shim_path.exists() else ""
    if previous == body:
        return False, "shim already points at detected app entry"
    shim_path.write_text(body, encoding="utf-8")
    return True, f"rewrote shim to point at {entry.rel_path}"


def _bump_timeout(path: Path) -> bool:
    """Double the most recent `timeout: <ms>` literal in a Playwright/jest test.
    Returns False if no timeout literal is found.
    """
    import re

    if not path.exists():
        return False
    src = path.read_text(encoding="utf-8")
    pattern = re.compile(r"timeout\s*:\s*(\d+)")
    last_match: re.Match | None = None
    for m in pattern.finditer(src):
        last_match = m
    if not last_match:
        return False
    current = int(last_match.group(1))
    new_val = current * 2
    new_src = src[: last_match.start(1)] + str(new_val) + src[last_match.end(1) :]
    path.write_text(new_src, encoding="utf-8")
    return True
